FROM mariadb:latest
MAINTAINER Boubacar <ouedraogoboubacar30@gmail.com>

VOLUME ["/var/lib/mysql"]

ENV MYSQL_ROOT_PASSORD=admin

COPY doc.sql /docker-entrypoint-initdb.d/
EXPOSE 3306

#Si besoin de créer une base de donnée avec des tables avec un script doc.sql

#RUN mysql -u root -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/doc.sql
