apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  labels:
    k8s-app: mariadb
spec:
  template:
    metadata:
      labels:
        k8s-app: mariadb
    spec:
      containers:
        - name: mariadb
          image: 192.168.99.1:5000/jenkins-mariadb
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:             
                secretKeyRef:
                  name: mariadb
                  key: password
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mariadb-storage
            subPath: mysql
          ports:
            - name: mariadb
              containerPort: 3306
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: pvc-mariadb
      imagePullSecrets:
      - name: registrycredential    
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    k8s-app: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    k8s-app: mariadb
    